djangoProjecteGitHub/djangoProject/djangoshop/djangoshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ecomapp.urls')),
]
#
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProjecteGitHub/djangoProject/djangoshop/ecomapp/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from ecomapp.views import (
    base_view,
    category_view,
    product_view,
    cart_view,
    add_to_cart_view,
    remove_from_cart_view,
    change_item_quantity,
    checkout_view,
    order_create_view,
    make_order_view,
    account_view,
    registration_view,
    login_view
    )

urlpatterns = [
    url(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
    url(r'^add_to_cart/$', add_to_cart_view, name='add_to_cart'),
    url(r'^remove_from_cart/$', remove_from_cart_view, name='remove_from_cart'),
    url(r'^change_item_quantity/$', change_item_quantity, name='change_item_quantity'),
    url(r'^cart/$', cart_view, name='cart'),
    url(r'^checkout/$', checkout_view, name='checkout'),
    url(r'^order/$', order_create_view, name='create_order'),
    url(r'^make_order/$', make_order_view, name='make_order'),
    url(r'^Thank_you/$', TemplateView.as_view(template_name='Thank_you.html'), name='Thank_you'),
    url(r'^account/$', account_view, name='account'),
    url(r'^registration/$', registration_view, name='registration'),
    url(r'^login/$', login_view, name='login'),
    url(r'^$', base_view, name='base'),

]

djangoProjecteGitHub/djangoProject/djangoshop/ecomapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()

    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})



class Type(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


class ProductManager(models.Manager):

    def all(self, *args, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)

class Product(models.Model):

    category = models.ForeignKey(Category, default=None)
    # type = models.ForeignKey(Type, None)
    title = models.CharField(max_length = 200)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=0)
    available = models.BooleanField(default=True)
    objects = ProductManager()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})


# class Book(models.Model):
#
#     BOOK_CHOICES = (
#         ('Fantasy', 'Thriller', 'Roman'),
#         ('Drama', 'Art'),
#     )
#     title = models.CharField(max_length = 100, choices = BOOK_CHOICES)

class CartItem(models.Model):

    product = models.ForeignKey(Product)
    quantity = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=0, default=0)



    def __unicode__(self):
        return "Cart item for product {0}".format(self.product.title)

class Cart(models.Model):

    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=0, default=0)

    def __unicode__(self):
        return str(self.id)

    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug = product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()

    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug = product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()


ORDER_STATUS_CHOICES = (
        ('Received for processing', 'Received for processing'),
        ('Processing', 'Processing'),
        ('Payed', 'Payed')
)

class Order(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    items = models.ManyToManyField(Cart)
    total = models.DecimalField(max_digits=9, decimal_places=0, default=0)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    buying_type = models.CharField(max_length=40, choices=(('Self', 'Self'), ('Delivery', 'Delivery')), default='Self')
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])


    def __unicode__(self):
        return "Order №{0}".format(str(self.id))

djangoProjecteGitHub/djangoProject/djangoshop/ecomapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from decimal import Decimal
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import login, authenticate
from ecomapp.forms import OrderForm, RegistrationForm, LoginForm
from ecomapp.models import Category, Product, CartItem, Cart, Order


def base_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total']=cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories' : categories,
        'products' : products,
    }
    return render(request, 'base.html', context)

def product_view(request, product_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total']=cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    context = {
        'product': product,
        'categories': categories,

    }
    return render(request, 'product.html', context)


def category_view(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    products_of_category = Product.objects.filter(category=category)
    context = {
        'category': category,
        'products_of_category':  products_of_category
    }
    return render(request, 'category.html', context)


def cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total']=cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'cart': cart
    }
    return render(request, 'cart.html', context)

def add_to_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total']=cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug = product_slug)
    cart.add_to_cart(product.slug)
    new_cart_total = 0
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})


def remove_from_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total']=cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug = product_slug)
    cart.remove_from_cart(product.slug)
    new_cart_total = 0
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})


def change_item_quantity(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total']=cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    quantity = request.GET.get('quantity')
    item_id = request.GET.get('item_id')
    cart_item = CartItem.objects.get(id=int(item_id))
    cart_item.quantity = int(quantity)
    cart_item.item_total = int(quantity) * Decimal(cart_item.product.price)
    cart_item.save()
    new_cart_total = 0
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse(
        {'cart_total': cart.items.count(),
        'item_total': cart_item.item_total,
        'cart_total_price': cart.cart_total})



def checkout_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total']=cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'cart':cart
    }
    return render(request, 'checkout.html', context)


def order_create_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total']=cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    context = {
        'form': form,
        'cart': cart
    }
    return render(request, 'order.html', context)



def make_order_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total']=cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        comments = form.cleaned_data['comments']


        # new_oreder = Order.objects.create(
        #     user = request.user,
        #     items = cart,
        #     total = cart.cart_total,
        #     first_name = first_name,
        #     last_name = last_name,
        #     phone = phonne,
        #     address = address,
        #     buying_type = buying_type,
        #     comments = comments
        # )
        new_order = Order()
        new_order.user = request.user
        new_order.save()
        new_order.items.add(cart)
        new_order.first_name = name
        new_order.last_name = last_name
        new_order.address = address
        new_order.buying_type = buying_type
        new_order.phone = phone
        new_order.comments = comments
        new_order.total = cart.cart_total
        new_order.save()
        # request.session['total']=cart.items.count()

        # (
        #     user=request.user,
        #     items=cart,
        #     first_name=name,
        #     last_name=last_name,
        #     phone=phone,
        #     address=address,
        #     buying_type=buying_type,
        #     date=date,
        #     comments=comments,
        # )

    del request.session['cart_id']
    del request.session['total']
    return HttpResponseRedirect(reverse('Thank_you'))
    # return render(request, 'order.html')



def account_view(request):
    order = Order.objects.filter(user=request.user).order_by('-id')
    context = {
        'order': order
    }
    return render(request, 'account.html', context)


def registration_view(request):
    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        new_user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        email = form.cleaned_data['email']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        new_user.username=username
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.email = email
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
        # username = form.cleaned_data['username']
        # password = form.cleaned_data['password']
        # login_user = authenticate(username=username, password=password)
        # if login_user:
        #     login(request, login_user)
    context = {
        'form': form
    }
    return render(request, 'registration.html', context)



def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))


    context = {
        'form': form
    }
    return render(request, 'login.html', context)

djangoProjecteGitHub/djangoProject/djangoshop/ecomapp/templates/Thank_you.html
{% extends 'base.html' %}


{% block content %}

<div class="col-sm-8 col-sm-offset-2">
  <h3 class="text-center">Thank you to your order! It's accepted to processing. Our manager will contact you</h3>
  <p class="text-center"><a href='/'><button class="btn btn-default">Back to order</button></a></p>
</div>

{% endblock content %}

djangoProjecteGitHub/djangoProject/djangoshop/ecomapp/templates/account.html
{% extends 'base.html' %}

{% block content %}

<h3 class="text-center">Profile of user {{request.user}}</h3>
<hr>

<h4 class="text-center">Your orders</h4>
<table class="table">
  <tr style="background:lightblue;">
    <td class="text-center">Number of order</td>
    <td class="text-center">Date of order</td>
    <td class="text-center">Status of order</td>
    <td class="text-center">Price of order</td>
    <td class="text-center">Details of order</td>
    <td class="text-center"></td>
  </tr>
{% for item in order %}
<tr>
  <td class="text-center" style="padding-top: 20px; paddint-bottom: 20px;">{{ item.id }}</td>
  <td class="text-center" style="padding-top: 20px; paddint-bottom: 20px;">{{ item.date }}</td>
  <td class="text-center" style="padding-top: 20px; paddint-bottom: 20px;">{{ item.status }}</td>
  <td class="text-center" style="padding-top: 20px; paddint-bottom: 20px;">{{ item.total }}</td>
  <td class="text-center" style="padding-top: 20px; paddint-bottom: 20px;"></td>
</tr>


{% endfor %}
</table>

{% endblock content %}

djangoProjecteGitHub/djangoProject/djangoshop/ecomapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/shop-homepage.css' %}?20191115" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url "base" %}">Book store</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  {% if not request.get_full_path == '/' %}
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category<span class="caret"></span></a>
                          <ul class="dropdown-menu">
                             { % for category in categories %}
                              <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                             { % endfor % }
                          </ul>
                      </li>
                  {% endif %}
                  {% if not request.user.is_authenticated %}
                  <li>
                    <p class="navbar-text">Hello guest</p>
                  </li>
                  <li>
                    <a href="{% url "login" %}">Sign in</a>
                  </li>
                  <li>
                    <a href="{% url "registration" %}">Register</a>
                  </li>
                  {% else %}
                  <li>
                    <p class="navbar-text">Hello, {{request.user }}</p>
                  </li>
                  <li>
                    <a href="{% url "account" %}">Lichni kabinet</a>
                  </li>
                  {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url "cart" %}">Basket <span class='badge' id="cart_count"></span></a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block content %}
        <div class="row">

            <div class="col-md-3">
                <p class="lead"></p>
                <div class="list-group">
                    {% for category in categories %}
                    <a href="{{ category.get_absolute_url }}" class="list-group-item">{{category.name}}</a>
                      <!-- <div class="sub-menu-1">
                          <ul>
                            <li><a href="#">Fantasy</li>
                            <li><a href="#">Thriller</li>
                            <li><a href="#">Drama</li>
                          </ul>
                      </div> -->
                    {% endfor %}
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="https://www.theyashelf.com/wp-content/uploads/2017/04/DM-Post_edited-1-e1492578853677-800x300.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>

                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>
                <br>
                <br>
                <br>
                <div class="row">
                    {% for product in products %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="{{ product.image.url }}" alt="" style="width: auto; height: 200px;">
                            <div class="caption">
                                <h5 class="pull-right">{{ product.price }} tenge.</h5>
                                <h5><strong><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></strong></a></h5>
                                <p>{{ product.description }}</p>
                            </div>
                        </div>
                    </div>
                      {% endfor %}

                </div>

            </div>

        </div>
        {% endblock content %}
    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/bootstrap.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/jquery.js' %}"></script>

<script>
$(document).ready(function(){
  $('.add_to_cart').on('click', function(e)
{
  e.preventDefault()
  product_slug = $(this).attr('data-slug')
  data = {
    type: "GET",
    url: '{% url "add_to_cart" %}',
    data: data,
    success: function(data){
      $("#cart_count").html(data.cart_total)
    }
  }
})
})
</script>

</body>

</html>

djangoProjecteGitHub/djangoProject/djangoshop/ecomapp/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h3 class="text-center">Basket</h3>
<br>
{% if cart.items.count > 0 %}
<div class="my-cart">
<table class="table">
<tr>
  <td class="text-center"><strong>Product</strong></td>
  <td class="text-center"><strong>Quantity</strong></td>
  <td class="text-center"><strong>Price</strong></td>
  <td class="text-center"></td>
</tr>
{% for item in cart.items.all %}
<tr class="cart-item-{{ item.product.id }}">
  <td class="text-center">{{ item.product.title }}</td>
  <td class="text-center">
      <form action="" method="GET">
        <input type="number" name="quantity" class="cart-item-quantity" data-id="{{ item.id }}" value="{{ item.quantity }}" min="1" style='width: 50px;'>
      </form>
  </td>
  <td class="text-center" id="cart-item-total-{{ item.id }}" >{{ item.item_total }} tenge</td>
  <td class="text-center"><a href="#" class="remove_from_cart" data-slug = "{{ item.product.slug }}" data-id="{{ item.product.id }}"><button class="btn btn-default">Delete</button></td>
</tr>
{% endfor %}
<tr>
  <td></td>
  <td class="text-center"><strong>Total:</strong></td>
  <td class="text-center" id="cart-total-price"><strong>{{ cart.cart_total }} tenge</strong></td>
  <td class="text-center"></td>

</tr>
</table>
<br>
<a href="{% url "checkout" %}" class="pull-right"><button class="btn btn-info">Preliminary order</button></a>
</div>
<h3 class="cart-empty"></h3>

{% else %}
<h3 class="text-center">Your basket is empty</h3>

{% endif %}
<script src="{% static 'js/jquery.js' %}"></script>
<script>
$(document).ready(function(){
  $('.cart-empty').css('display', 'none')
  $('.remove_from_cart').on('click', function(e){
    e.preventDefault()
    product_slug = $(this).attr('data-slug')
    // console.log(product_slug)
    item_product_id = $(this).attr('data-id')
    console.log(item_product_id)

    data = {
      product_slug: product_slug
    }

    $.ajax({
      type: "GET",
      url: '{% url "remove_from_cart" %}',
      data: data,
      success: function(data){
        $("#cart_count").html(data.cart_total)
        $('.cart-item-'+item_product_id).css('display', 'none')
        $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(0) + ' tenge </strong>')
        if(parseInt(data.cart_total) == 0)
        {
          $('.my-cart').css('display', 'none')
          $('.cart-empty').css('display', 'block')
          $('.cart-empty').html('<h3 class="text-center">Your basket is empty</h3>')
        }

      }
    })
  })
})

$(document).ready(function(){
  $('.cart-item-quantity').on('click', function(){
    quantity = $(this).val()
    item_id = $(this).attr('data-id')
    // console.log(quantity)
    // console.log(item_id)
    data = {
      quantity: quantity,
      item_id: item_id

    }
    $.ajax({
      type: "GET",
      url: '{% url "change_item_quantity" %}',
      data: data,
      success: function(data){
        $('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(0) + ' tenge')
        $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(0) + ' tenge </strong>')
      }
    })
  })
})
</script>
<!-- <script>
$(document).ready(function(){

})
</script> -->
{% endblock content %}

djangoProjecteGitHub/djangoProject/djangoshop/ecomapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class="text-center">Sign In</h3>
<hr>
<div class="col-sm-8 col-sm-offset-2">
<form action="" method="">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-success btn-block" value="Enter">
</form>
</div>

{% endblock content %}

djangoProjecteGitHub/djangoProject/djangoshop/ecomapp/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<form action="{% url "make_order" %}" method="POST">
{% csrf_token %}
<div class="col-sm-4">
  {{ form.name|as_crispy_field }}
</div>
<div class="col-sm-4">
  {{ form.last_name|as_crispy_field }}
</div>
<div class="col-sm-4">
  {{ form.phone|as_crispy_field }}
</div>
{{ form.buying_type|as_crispy_field }}
{{ form.address|as_crispy_field }}
{{ form.date|as_crispy_field }}
{{ form.comments|as_crispy_field }}
<input type="submit" class="btn btn-success" value="Order a product" >
<!-- <li>
  <></a>
</li> -->
<!-- <a href="{% url "make_order" %}"></a> -->
</form>
<script src="{% static 'js/jquery.js' %}"></script>
<script>
  // // $(document).ready(function(){
  // //   $('#div_id_address').css('display', 'none')
  // //   $('#id_buying_type').on('click', function(){
  // //     buying_type = $(this).val()
  // //     // console.log(buying_type)
  // //     if(buying_type == 'Delivery'){
  // //       $('#div_id_address').css('display', 'block')
  // //     }else{
  // //       $('#div_id_address').css('display', 'none')
  // //     }
  // //   })
  // })
        $(document).ready(function(){
          $('#id_date_month').css('width', '100px')
          $('#id_date_month').css('display', 'inline')
          $('#id_date_year').css('width', '100px')
          $('#id_date_year').css('display', 'inline')
          $('#id_date_day').css('width', '50px')
          $('#id_date_day').css('display', 'inline')


        })


</script>
{% endblock content %}